# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5416289ee66a4868265611378045305b46c610b4af10ff05d1f96e7fb042bb984f9bbc8e5eb6002705231985ae1a5ecfdde69c467150244013045a9bc2b659c4

test:
  secret_key_base: d5947372636ee28948af7eb40093a94fee03d2e0771f4c35349a04ee749242365590e6ae99ef66f65c4bb52ba0304478fd64f5dd5dd43c1700e099c1fb60c741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
